import type { NextPage } from "next";
import Head from "next/head";
import {
  ContentContainer,
  GlobalContainer,
  MainContainer,
} from "../components/Containers";
import Header from "../components/Header";
import Atom from "../components/Atom";
import Presentation from "../components/Presentation";

const Home: NextPage = () => {
  return (
    <GlobalContainer>
      <Head>
        <title>Saul Moreyra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ContentContainer>
        <Header />
        <MainContainer>
          <Presentation />
          <Atom />
        </MainContainer>
        <footer></footer>
      </ContentContainer>
    </GlobalContainer>
  );
};

export default Home;
