import type { NextPage } from "next";
import Head from "next/head";
import GlobalContainer from "../components/Containers/GlobalContainer";
import { MainContainer } from "../components/Containers";
import Header from "../components/Header";

const Home: NextPage = () => {
  return (
    <GlobalContainer>
      <Head>
        <title>Saul Moreyra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContainer>
        <Header />
        <main></main>
        <footer></footer>
      </MainContainer>
    </GlobalContainer>
  );
};

export default Home;
