import type { NextPage } from "next";
import Head from "next/head";
import { ContentContainer, GlobalContainer } from "components/Containers";
import Header from "components/Header";
import Views from "views";

const Home: NextPage = () => {
  return (
    <GlobalContainer>
      <Head>
        <title>Saul Moreyra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <ContentContainer>
        <Views />
      </ContentContainer>
    </GlobalContainer>
  );
};

export default Home;
