export { default as IconMoon } from "./Moon";
export { default as IconSun } from "./Sun";
export { default as IconInstagram } from "./Instagram";
export { default as IconFacebook } from "./Facebook";
export { default as IconGithub } from "./Github";
export { default as IconLinkedin } from "./Linkedin";
export { default as IconExit } from "./Exit";
export { default as IconHamburger } from "./Hamburger";
export { default as IconArrow } from "./Arrow";
